---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: false
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- ".idea/*"
- design/*
- dokumentation/*
- dokumentation/UML/*
- SQL/*
- include/GoogleAuthenticator/*
- include/GoogleAuthenticator/exemple/*
- include/GoogleAuthenticator/PHPGansta/*
- include/GoogleAuthenticator/tests/*
- include/Highcharts-4.2.1/*
- include/Highcharts-4.2.1/api/*
- include/Highcharts-4.2.1/api/css/*
- include/Highcharts-4.2.1/api/fonts/*
- include/Highcharts-4.2.1/api/js/*
- include/Highcharts-4.2.1/js/*
- include/Highcharts-4.2.1/js/adapters/*
- include/Highcharts-4.2.1/js/modules/*
- include/Highcharts-4.2.1/js/modules/themes/*